import type { Project, UserProfile } from "./types";

export const mockUsers: UserProfile[] = [
  { id: "demo-admin", name: "Carlos Wiebe", email: "admin@cbdevs.local", role: "admin", active: true },
  { id: "demo-dev", name: "Socio CBDEVS", email: "dev@cbdevs.local", role: "empleado", active: true },
];

export const mockProjects: Project[] = [
  {
    id: "p-sovesoul",
    name: "SOVE|SOUL",
    client: "SOVE|SOUL",
    serviceType: "Sitio Web",
    deliveryStatus: "En desarrollo",
    paymentStatus: "Pago inicial recibido",
    currency: "MXN",
    amount: 28000,
    initialPayment: 14000,
    monthlyMaintenance: 850,
    startDate: "2026-08-01",
    estimatedDelivery: "2026-09-25",
    nextMaintenanceDate: "2026-10-05",
    responsibleIds: ["demo-admin", "demo-dev"],
    notes: "E-commerce premium streetwear. Firebase Auth + Firestore/Realtime Database.",
    repoUrl: "https://github.com/",
    productionUrl: "https://sovesoul.web.app/",
  },
  {
    id: "p-internal",
    name: "CBDEVS Internal Portal",
    client: "CBDEVS",
    serviceType: "Software Personalizado/Automatización",
    deliveryStatus: "En desarrollo",
    paymentStatus: "Pagado completo",
    currency: "MXN",
    amount: 0,
    initialPayment: 0,
    monthlyMaintenance: 0,
    startDate: "2026-09-01",
    estimatedDelivery: "2026-10-10",
    responsibleIds: ["demo-admin"],
    notes: "Dashboard administrativo interno para operación del estudio.",
  },
  {
    id: "p-inventory",
    name: "IMT-PORTAL",
    client: "IMT",
    serviceType: "Aplicación Web",
    deliveryStatus: "En mantenimiento",
    paymentStatus: "Mantenimiento al día",
    currency: "MXN",
    amount: 42000,
    initialPayment: 21000,
    monthlyMaintenance: 1200,
    startDate: "2026-03-15",
    estimatedDelivery: "2026-05-30",
    actualDelivery: "2026-05-27",
    nextMaintenanceDate: "2026-09-15",
    responsibleIds: ["demo-dev"],
    notes: "Inventario, checador, agenda y exportación a Excel.",
  },
  {
    id: "p-demo",
    name: "Landing Azenzo",
    client: "Azenzo",
    serviceType: "Sitio Web",
    deliveryStatus: "Entregado",
    paymentStatus: "Pagado completo",
    currency: "MXN",
    amount: 16000,
    initialPayment: 8000,
    monthlyMaintenance: 600,
    startDate: "2026-04-02",
    estimatedDelivery: "2026-04-28",
    actualDelivery: "2026-04-25",
    nextMaintenanceDate: "2026-09-20",
    responsibleIds: ["demo-admin"],
    notes: "Landing comercial entregada.",
  },
];
